version: '3.3'

services:
  db:
    image: postgres:13-alpine
    container_name: node_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=film

volumes:
  postgres_data: